# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_alter_userbankaccount_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposit_date',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='date_of_opening',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9738202474', unique=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(choices=[('S', 'SILVER'), ('G', 'GOLD'), ('P', 'PLATINUM')], max_length=1),
        ),
    ]
