# Generated by Django 3.2.9 on 2021-11-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20211129_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9615536526', unique=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accountapp.user_model'),
        ),
    ]
