# Generated by Django 3.2.9 on 2021-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_auto_20211129_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='balance',
            new_name='initial_balance',
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9796901254', unique=True),
        ),
    ]
