# Generated by Django 3.2.9 on 2021-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_auto_20211205_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='status',
            field=models.BooleanField(auto_created=True, default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9518710606', unique=True),
        ),
    ]
