# Generated by Django 3.2.12 on 2022-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_auto_20211206_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9398411353', unique=True),
        ),
    ]
