# Generated by Django 4.0.1 on 2022-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_auto_20211206_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9872057300', unique=True),
        ),
    ]
