# Generated by Django 3.2 on 2021-11-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_auto_20211130_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountapp.user_model'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(default='9436702252', unique=True),
        ),
    ]
